/* eslint-disable */
/* global WebImporter */

/**
 * Transformer: temasekreview.com.sg site-wide cleanup.
 *
 * All selectors are taken from the captured DOM in migration-work/cleaned.html.
 * The scraper already omits the site navigation (see the
 * "<!-- NAVIGATION (auto-populated by EDS header) omitted -->" placeholder),
 * so the header/footer chrome is handled by the EDS shell, not authored content.
 * This transformer removes the remaining non-authorable / presentational chrome
 * and normalizes layout/tracking attributes so the import contains only
 * page-level authorable content.
 */
const TransformHook = { beforeTransform: 'beforeTransform', afterTransform: 'afterTransform' };

export default function transform(hookName, element, payload) {
  if (hookName === TransformHook.beforeTransform) {
    // Decorative masthead background image wrapper (alt="", print-hide).
    // Found in captured DOM: <div class="hero-banner__background print-hide">
    // Not authorable content - purely presentational chrome behind the hero.
    //
    // The remaining selectors are site-shell chrome present on the LIVE page
    // (not in the scraped cleaned.html) that is auto-generated by the EDS
    // header/footer, not authorable page content:
    //   #skip-to-main            - a11y skip link
    //   .tr-navigation           - in-page nav (menu, PDF download, language,
    //                              social share, search) that sits at the top
    //                              of .page-body
    //   footer.main-footer       - site footer (quick links, channels, legal)
    //   #disclaimer-box          - global financial disclaimer footer band
    //   #cookieConsent / cookie  - cookie consent banner + dialog + toast
    WebImporter.DOMUtils.remove(element, [
      '.hero-banner__background',
      '#skip-to-main',
      '.tr-navigation',
      'footer',
      '.main-footer',
      '#disclaimer-box',
      '#cookieConsent',
      '.cookieConsent',
      '.ct-container',
      '[role="dialog"]',
      'script',
      'style',
      'noscript',
    ]);

    // Chapter banners ship two <picture> variants inside .content-box__banner:
    // a screen one (class "print-hide") and a print-only one (class
    // "print-show", the "-d" asset, display:none on screen). Keep only the
    // screen variant so the migrated page shows a single banner per chapter.
    element.querySelectorAll('.print-show').forEach((el) => {
      const pic = el.closest('picture') || el;
      pic.remove();
    });
  }

  if (hookName === TransformHook.afterTransform) {
    // Any global chrome that may appear on the live shell but is not authorable.
    // (cleaned.html has these stripped; guarded so removal is a no-op when absent.)
    WebImporter.DOMUtils.remove(element, [
      'header',
      'footer',
      'nav',
      '.tr-navigation',
      '#disclaimer-box',
      '#cookieConsent',
      '.cookieConsent',
      '.ct-container',
      '[role="dialog"]',
      'iframe',
      'link',
      'noscript',
    ]);

    // Strip presentation / tracking attributes found in the captured DOM
    // (data-vertical-align on .row layout wrappers, data-video-id / aria-label
    // on the community video anchors) so only authorable structure remains.
    element.querySelectorAll('*').forEach((el) => {
      el.removeAttribute('data-vertical-align');
      el.removeAttribute('data-video-id');
      el.removeAttribute('onclick');
    });

    // DA delivers SVGs as CONTENT with a hard 20KB limit (AEM_BACKEND_SVG_TOO_BIG),
    // so html2md rejects the large infographic SVGs on preview/publish. These are
    // static, non-interactive charts, so we pre-rasterised them to PNG (Media Bus
    // has no such limit) committed under /assets/charts/ and remap the oversized
    // originals here. Small logos / lockups (<20KB) are left as SVG.
    const OVERSIZED_SVG_TO_PNG = {
      'TRM26_Operating_as_One_Temasek.svg': 'TRM26_Operating_as_One_Temasek.png',
      'TRM26_10Years_Net_Portfolio_Value.svg': 'TRM26_10Years_Net_Portfolio_Value.png',
      'TRM26_Total_Shareholder_Return_wof.svg': 'TRM26_Total_Shareholder_Return_wof.png',
      'TRM26_Towards_Net_Zero_wof.svg': 'TRM26_Towards_Net_Zero_wof.png',
      'TRM26_Three_Segment_T2030_Strategy.svg': 'TRM26_Three_Segment_T2030_Strategy.png',
      'TRM26_Four_Pillars_of_Temaseks_AI_Strategy.svg': 'TRM26_Four_Pillars_of_Temaseks_AI_Strategy.png',
      // Performance & Portfolio oversized charts
      'TRM26_Key_Investments_and_Divestments_for_the_Year.svg': 'TRM26_Key_Investments_and_Divestments_for_the_Year.png',
      'TRM26_Promising_New_Areas.svg': 'TRM26_Promising_New_Areas.png',
      'TRM26_Asset_Management_Companies.svg': 'TRM26_Asset_Management_Companies.png',
      'TRM26_Portfolio_Returns_by_Portfolio_Segments.svg': 'TRM26_Portfolio_Returns_by_Portfolio_Segments.png',
      'TRM26_Volatility_of_Returns.svg': 'TRM26_Volatility_of_Returns.png',
      'TRM26_Portfolio_by_Underlying_Sector_Exposure.svg': 'TRM26_Portfolio_by_Underlying_Sector_Exposure.png',
      'TRM26_Global_Direct_Investments_by_Headquarters.svg': 'TRM26_Global_Direct_Investments_by_Headquarters.png',
      'TRM26_Global_Direct_Investments_by_Sector.svg': 'TRM26_Global_Direct_Investments_by_Sector.png',
      'TRM26_Illustration_of_Fundamental_Earnings_Impact.svg': 'TRM26_Illustration_of_Fundamental_Earnings_Impact.png',
      'TRM26_Portfolio_by_Headquarters_and_Underlying_Country_Exposure.svg': 'TRM26_Portfolio_by_Headquarters_and_Underlying_Country_Exposure.png',
      'TRM26_Portfolio_by_Currency.svg': 'TRM26_Portfolio_by_Currency.png',
      // Institution oversized charts
      'TRM26_Protection_of_Temasek_Past_Reserves.svg': 'TRM26_Protection_of_Temasek_Past_Reserves.png',
      'TRM26_WA_Incentives_Key_Team.svg': 'TRM26_WA_Incentives_Key_Team.png',
      // Employee-demographics slider: three views x three geographies. We
      // rasterized the default Global view of each; the Singapore / Outside-SG
      // variants (all >20KB, so unusable as SVG on DA) fall back to the Global
      // PNG so no oversized SVG reference survives.
      'TRM26_Employees_by_Nationality_Global.svg': 'TRM26_Employees_by_Nationality_Global.png',
      'TRM26_Employees_by_Nationality_Singapore.svg': 'TRM26_Employees_by_Nationality_Global.png',
      'TRM26_Employees_by_Nationality_Outside_of_Singapore.svg': 'TRM26_Employees_by_Nationality_Global.png',
      'TRM26_Employees_by_Age_Global.svg': 'TRM26_Employees_by_Age_Global.png',
      'TRM26_Employees_by_Age_Singapore.svg': 'TRM26_Employees_by_Age_Global.png',
      'TRM26_Employees_by_Age_Outside_of_Singapore.svg': 'TRM26_Employees_by_Age_Global.png',
      'TRM26_Employees_by_Gender_Global.svg': 'TRM26_Employees_by_Gender_Global.png',
      'TRM26_Employees_by_Gender_Singapore.svg': 'TRM26_Employees_by_Gender_Global.png',
      'TRM26_Employees_by_Gender_Outside_of_Singapore.svg': 'TRM26_Employees_by_Gender_Global.png',
    };
    const CHART_BASE = '/assets/charts';
    element.querySelectorAll('img[src$=".svg"], img[src*=".svg?"]').forEach((img) => {
      const src = img.getAttribute('src') || '';
      const file = src.split('/').pop().split('?')[0];
      if (OVERSIZED_SVG_TO_PNG[file]) {
        img.setAttribute('src', `${CHART_BASE}/${OVERSIZED_SVG_TO_PNG[file]}`);
      }
    });
  }
}
